# Generated by Django 5.2.1 on 2025-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='TeacherUsersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('juda_ham_qoniqaman', models.IntegerField(default=0)),
                ('ortacha_qoniqaman', models.IntegerField(default=0)),
                ('asosan_qoniqaman', models.IntegerField(default=0)),
                ('qoniqmayman', models.IntegerField(default=0)),
                ('umuman_qoniqaman', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.CharField(default='0', max_length=20)),
                ('topics', models.ManyToManyField(blank=True, to='main.teachertopic')),
            ],
            options={
                'verbose_name': "O'qituvchining statistikasi",
                'verbose_name_plural': "O'qituvchilarning statistikasi",
                'ordering': ['-updated_at'],
            },
        ),
    ]
